### ISSUE TITLE
Filter by emotion, other types

### ISSUE THREAD

**Issue by ngoldman** [maxogden/cool-ascii-faces#12]
Would be ideal to create a readable stream of angry or depressed faces for different situations. http://japaneseemoticons.net/ has a decent taxonomy that could be used as a model.

**Comment by kid-icarus** [comment]
yo check it https://github.com/kid-icarus/lysergix

**Comment by maxogden** [comment]
ahahahahaha

**Comment by ngoldman** [comment]
(〃⌒▽⌒)八(〃⌒▽⌒〃)八(⌒▽⌒〃)
